### ISSUE TITLE
Weird parsing of escaped characters

### ISSUE THREAD

**Issue by rirze** [pier-cli/pier#23]
Hi, I'm trying to add a one-liner with this snippet in it:
```sed -r "s/^[0-9.]+\s+//"```
However, when it gets parsed, this part of the command transforms to:
```sed -r s/^[0-9.]+s+//```

Once I replaced `\s` with `[ ]`, the command parsed correctly. Is this a bug or something I have to work around?

**Comment by BenSchZA** [comment]
Hey @rirze I believe that's a bug. I'll figure out if there's an easy way to handle it, or of there's a workaround. I know @Plommonsorbet recently updated some of that logic, so might have a better idea of how it works currently.

**Comment by BenSchZA** [comment]
Basically what's happening is your shell (bash for example) is parsing the command, parsing shell escapes, and then running the command. So that \s is being escaped and the backslash is removed. That's my initial theory. Will test later.

**Comment by BenSchZA** [comment]
If you can get the script working in your terminal with your specific shell, then it'll work with Pier. For example `$SHELL -c "echo "hello""`.

Interestingly, something we could look into is using `printf` to implement string escaping. When applied to your example `printf "%q" "sed -r 's/^[0-9.]+\s+//'"` - you get the following result, which seems to work with Pier: `sed\ -r\ \'s/\^\[0-9.\]+\\s+//\'`

See https://stackoverflow.com/questions/2854655/command-to-escape-a-string-in-bash

**Comment by rirze** [comment]
I'm not sure I follow. For example, I can execute the snippet fine in my shell. The fault lies when the terminal is interpreting the string as Pier is saving it.

I guess, using your example:
```bash
user@server:~$ $SHELL -c "echo 'sed -r "s/^[0-9.]+\s+//"'"
sed -r s/^[0-9.]+s+//
```

I think your second example could work though.

**Comment by Plommonsorbet** [comment]
Hi,

The behavior is quite odd because it doesn't seem to be in line with how normal shell escaping works which makes me 
believe it has something to do with how clap handles the string or how it's deserialized to toml later.

I think it's something to do with how clap the cli argument parsing works, it seems if you use double quotes 
it doesn't seem to see the string as a raw string literal. 

However the examples work fine when using single quotes:
pier add 'sed -r "s/^[0-9.]+\s+//"' --alias test-cmd

Turns into:
[scripts.test-cmd]
alias = 'test-cmd'
command = 'sed -r "s/^[0-9.]+\s+//"'

So for now i think the best solution is just to wrap the command part in single quotes.

However perhaps we should come up with a better method of adding the command outside of specifying it in the shell command?
Some example method:

* Pier add opens the command in section in the editor defined by $EDITOR.
* Pier add gives you an input field to enter the command into.

The methods could be added with different context flags perhaps?

Let me know if I was unclear about something. :)

**Comment by BenSchZA** [comment]
You're correct, the fault does lie when the shell is interpreting it as it's being saved. So either you have to use single quotes, or escape it properly - which is what the printf command was doing :) This thread seems to clear up the single vs double quote handling: https://stackoverflow.com/questions/6697753/difference-between-single-and-double-quotes-in-bash

> Enclosing characters in double quotes (") preserves the literal value of all characters within the quotes, with the exception of $, `, \, and, when history expansion is enabled, !. The characters $ and ` retain their special meaning within double quotes (see Shell Expansions).

**Comment by BenSchZA** [comment]
It's also going through two rounds of shell expansion essentially, one when passing to the Pier command, and one when the script is run from the yaml file using `bash -c ...`.

**Comment by BenSchZA** [comment]
I think the simplest solution would be to add documentation for this behaviour. In future I think it's reasonable to expect that the CLI follows normal shell escaping rules (unless I'm mistaken and it doesn't, or there's an issue it causes that's specifically related to Pier).

**Comment by Plommonsorbet** [comment]
Most of the time it's not an issue but with some onen liners it can become quite convoluted and I think in those cases it would be nice with just a way to paste in the working command. Another nice bonus of opening the command in the editor is that it would allow easy access to modifying an existing command.

**Comment by rirze** [comment]
Just want to note-- if I pasted the same command/snippet directly into my `.pier` config, the script runs fine. I think this problem only lies when saving/updating commands from the command line. What I mean is that Pier has no problem afaik interpreting and running commands that are already saved.

**Comment by Plommonsorbet** [comment]
Implemented the functionality to open the $EDITOR when no argument is passed to the add function in PR #31.

e.g. In this pull request the following script will create a command with alias 'my_alias' and then open the $EDITOR for writing/editing the command.
```pier add -a my_alias ```
