### ISSUE TITLE
Show output to stderr as it happens.

### ISSUE THREAD

**Issue by korrat** [pier-cli/pier#65]
I'm using a shell script managed by pier to perform various update tasks. One of these tasks is running `rustup update`. Currently, when I run this script, some of the progress output goes to stderr and is only visible after the whole script finishes. I think it would be better to show stderr output as it is produced by the script subprocess.

I think the issue might stem from [this line](https://github.com/pier-cli/pier/blob/master/src/script.rs#L49).

**Comment by Plommonsorbet** [comment]
Hey, thanks for the issue. 

Sorry about  not replying very quickly, decided to do a tech detox while on a vacation so I'm just getting back to these now.

The issue is as you mentioned that line so it'll be a quick fix, you can send a pull request if you want to fix it. Or I can make one and give you credit! 

Maybe a cool idea would be to set the colour on the output text to green / red or orange depending if the line is stdout or stderr, would you find that useful in your usage do you think? :)

**Comment by Plommonsorbet** [comment]
Like I mentioned in the pull request, I'm leaving this issue up until I've figured out a regression test for this. Probably going to be toying around with it today and tomorrow night. If you have any input on this it's very much appreciated! :)
